List<Map<String, dynamic>> stockData = [
  {
    'id': 1,
    'nama': 'Laptop',
    'title': 'Elektronik',
    'deskripsi': 'Laptop dengan spesifikasi tinggi untuk kebutuhan komputasi',
    'tanggal_masuk': '2023-08-01',
  },
  {
    'id': 2,
    'nama': 'Baju',
    'title': 'Pakaian',
    'deskripsi': 'Baju casual berwarna biru dengan desain modern',
    'tanggal_masuk': '2023-08-05',
  },
  {
    'id': 3,
    'nama': 'Buku',
    'title': 'Alat Tulis',
    'deskripsi': 'Buku panduan belajar matematika tingkat dasar',
    'tanggal_masuk': '2023-07-15',
  },
  {
    'id': 4,
    'nama': 'Mouse',
    'title': 'Elektronik',
    'deskripsi': 'Mouse optik dengan desain ergonomis',
    'tanggal_masuk': '2023-08-10',
  },
  {
    'id': 5,
    'nama': 'Laptop',
    'title': 'Elektronik',
    'deskripsi': 'Laptop dengan spesifikasi tinggi untuk kebutuhan komputasi',
    'tanggal_masuk': '2023-08-05',
  },
  {
    'id': 6,
    'nama': 'Kemeja',
    'title': 'Pakaian',
    'deskripsi': 'Kemeja formal berwarna putih dengan bahan berkualitas',
    'tanggal_masuk': '2023-08-12',
  },
  {
    'id': 7,
    'nama': 'Pensil',
    'title': 'Alat Tulis',
    'deskripsi': 'Pensil dengan kualitas terbaik untuk menulis',
    'tanggal_masuk': '2023-08-02',
  },
  {
    'id': 8,
    'nama': 'Keyboard',
    'title': 'Elektronik',
    'deskripsi': 'Keyboard mekanik untuk para gamer',
    'tanggal_masuk': '2023-07-25',
  },
  {
    'id': 9,
    'nama': 'Kemeja',
    'title': 'Pakaian',
    'deskripsi': 'Kemeja casual berwarna hitam dengan desain keren',
    'tanggal_masuk': '2023-08-08',
  },
  {
    'id': 10,
    'nama': 'Buku',
    'title': 'Alat Tulis',
    'deskripsi': 'Buku novel bestseller tentang petualangan di dunia fantasi',
    'tanggal_masuk': '2023-08-03',
  },
  {
    'id': 11,
    'nama': 'Celana',
    'title': 'Pakaian',
    'deskripsi': 'Celana jeans berwarna biru dengan potongan modern',
    'tanggal_masuk': '2023-08-06',
  },
  {
    'id': 12,
    'nama': 'Printer',
    'title': 'Elektronik',
    'deskripsi': 'Printer multifungsi dengan kemampuan cetak tinggi',
    'tanggal_masuk': '2023-07-28',
  },
  {
    'id': 13,
    'nama': 'Meja',
    'title': 'Furniture',
    'deskripsi': 'Meja kerja dengan desain minimalis',
    'tanggal_masuk': '2023-08-04',
  },
  {
    'id': 14,
    'nama': 'Buku',
    'title': 'Alat Tulis',
    'deskripsi': 'Buku panduan belajar bahasa asing dengan mudah',
    'tanggal_masuk': '2023-07-20',
  },
  {
    'id': 15,
    'nama': 'Baju',
    'title': 'Pakaian',
    'deskripsi': 'Baju santai berwarna merah dengan kenyamanan tinggi',
    'tanggal_masuk': '2023-08-09',
  },
  {
    'id': 16,
    'nama': 'Kemeja',
    'title': 'Pakaian',
    'deskripsi': 'Kemeja formal berwarna biru dengan kualitas terbaik',
    'tanggal_masuk': '2023-07-18',
  },
  {
    'id': 17,
    'nama': 'Keyboard',
    'title': 'Elektronik',
    'deskripsi': 'Keyboard dengan fitur anti-ghosting untuk penggunaan gaming',
    'tanggal_masuk': '2023-08-14',
  },
  {
    'id': 18,
    'nama': 'Buku',
    'title': 'Alat Tulis',
    'deskripsi': 'Buku panduan belajar seni lukis untuk pemula',
    'tanggal_masuk': '2023-08-07',
  },
  {
    'id': 19,
    'nama': 'Kamera',
    'title': 'Elektronik',
    'deskripsi': 'Kamera digital dengan resolusi tinggi untuk fotografi',
    'tanggal_masuk': '2023-07-22',
  },
  {
    'id': 20,
    'nama': 'Sepatu',
    'title': 'Pakaian',
    'deskripsi': 'Sepatu olahraga dengan desain modern dan nyaman',
    'tanggal_masuk': '2023-08-11',
  },
  {
    'id': 21,
    'nama': 'Buku',
    'title': 'Alat Tulis',
    'deskripsi': 'Buku panduan belajar musik untuk pemula',
    'tanggal_masuk': '2023-08-13',
  },
  {
    'id': 22,
    'nama': 'Kemeja',
    'title': 'Pakaian',
    'deskripsi': 'Kemeja casual berwarna abu-abu dengan desain simpel',
    'tanggal_masuk': '2023-07-26',
  },
  {
    'id': 23,
    'nama': 'Laptop',
    'title': 'Elektronik',
    'deskripsi': 'Laptop dengan spesifikasi tinggi untuk produktivitas',
    'tanggal_masuk': '2023-08-17',
  },
  {
    'id': 24,
    'nama': 'Buku',
    'title': 'Alat Tulis',
    'deskripsi': 'Buku panduan belajar memasak makanan internasional',
    'tanggal_masuk': '2023-08-19',
  },
  {
    'id': 25,
    'nama': 'Mouse',
    'title': 'Elektronik',
    'deskripsi': 'Mouse nirkabel dengan desain ergonomis',
    'tanggal_masuk': '2023-08-23',
  },
  {
    'id': 26,
    'nama': 'Pensil',
    'title': 'Alat Tulis',
    'deskripsi': 'Pensil mekanik dengan berbagai ketebalan ujung',
    'tanggal_masuk': '2023-08-21',
  },
  {
    'id': 27,
    'nama': 'Celana',
    'title': 'Pakaian',
    'deskripsi': 'Celana panjang berwarna hitam dengan desain elegan',
    'tanggal_masuk': '2023-08-25',
  },
  {
    'id': 28,
    'nama': 'Baju',
    'title': 'Pakaian',
    'deskripsi': 'Baju formal berwarna putih dengan kualitas terbaik',
    'tanggal_masuk': '2023-08-27',
  },
  {
    'id': 29,
    'nama': 'Printer',
    'title': 'Elektronik',
    'deskripsi': 'Printer laser monokrom dengan kecepatan cetak tinggi',
    'tanggal_masuk': '2023-08-29',
  },
  {
    'id': 30,
    'nama': 'Buku',
    'title': 'Alat Tulis',
    'deskripsi': 'Buku panduan belajar matematika tingkat lanjutan',
    'tanggal_masuk': '2023-08-31',
  },
  // ... tambahkan data stok lainnya ...
];
